apiVersion: v1
kind: Service
metadata:
  name: grip-api-service
  labels:
    app: grip-api-app
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  selector:
    app: grip-api-app
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.port }}