apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grip-api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  namespace: {{ .Release.Namespace | quote }}
spec:
  tls:
    - secretName: api-tls-secret
      hosts:
      - {{ .Values.hostname }}
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /(api(?:/|$).*)
            pathType: Prefix        
            backend:
              service:              
                name: grip-api-service
                port:
                  number: {{ .Values.port }}
