trigger:
  - master
  - azure-pipelines

pr: none  
  
pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  solutionPath: './GRIP.Api/Grip.Api.sln'
  app_service_name: GripAPI

stages:
- template: templates/build-stage.yml

- template: templates/release-stage.yml
  parameters:
    environment: DEV
    app_service_name: $(app_service_name)
    azure_service_connection: 'Grip - CD'

- template: templates/release-stage.yml
  parameters:
    environment: STG
    dependsOn: Publish_DEV
    app_service_name: $(app_service_name)
    azure_service_connection: 'Grip - stage'
      
- template: templates/release-stage.yml
  parameters:
    environment: PRD
    dependsOn: Publish_STG
    app_service_name: $(app_service_name)
    azure_service_connection: 'Grip - Production'