trigger:
  - main

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  artifactName: "terraform"
  terraformVersion: "0.15.0"
  workingDirectory: "$(Pipeline.Workspace)/$(artifactName)"
  
stages:
  # We need to publish the source to the artifacts folder so we can use it in multiple stages
  - template: azure-devops-templates/copy-files.yml

  # Development environment
  - template: azure-devops-templates/terraform.yml
    parameters:
      environment: dev-01
      azure_service_connection: "Grip - Non Prod - ADO Service Connection"
      tfstate_storage_account: "infranonprod"
      azdo_environment_suffix: "-review"
      depends_on: publish

  # Staging environment
  - template: azure-devops-templates/terraform.yml
    parameters:
      environment: stage-01
      azure_service_connection: "Grip - Non Prod - ADO Service Connection"
      tfstate_storage_account: "infranonprod"
      depends_on: TerraformApply_dev_auea_01

  # Production environment
  - template: azure-devops-templates/terraform.yml
    parameters:
      environment: prod-01
      azure_service_connection: "Grip - Prod - ADO Service Connection"
      tfstate_storage_account: "infranonprod"
      depends_on: TerraformApply_stage_auea_01
